### ISSUE TITLE
Colormap not found if installed from pip

### ISSUE THREAD

**Issue by milancurcic** [intake/xrviz#17]
I just tried out the example in xrviz following your Medium blog post. Not a conda user, so installed from pip. If I try to plot a variable, I hit a ValueError due to missing colormap, see full traceback:

```
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f08a3475390>>, <Future finished exception=ValueError('Supplied cmap fire not found among matplotlib, bokeh, or colorcet colormaps.',)>)
Traceback (most recent call last):
  File "/home/milan/Work/xrviz/venv/lib/python3.6/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/milan/Work/xrviz/venv/lib/python3.6/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/home/milan/Work/xrviz/venv/lib/python3.6/site-packages/tornado/gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "/home/milan/Work/xrviz/venv/lib/python3.6/site-packages/bokeh/server/session.py", line 70, in _needs_document_lock_wrapper
    result = yield yield_for_all_futures(func(self, *args, **kwargs))
  File "/home/milan/Work/xrviz/venv/lib/python3.6/site-packages/bokeh/server/session.py", line 191, in with_document_locked
    return func(*args, **kwargs)
  File "/home/milan/Work/xrviz/venv/lib/python3.6/site-packages/bokeh/document/document.py", line 1127, in wrapper
    return doc._with_self_as_curdoc(invoke)
  File "/home/milan/Work/xrviz/venv/lib/python3.6/site-packages/bokeh/document/document.py", line 1113, in _with_self_as_curdoc
    return f()
  File "/home/milan/Work/xrviz/venv/lib/python3.6/site-packages/bokeh/document/document.py", line 1126, in invoke
    return f(*args, **kwargs)
  File "/home/milan/Work/xrviz/venv/lib/python3.6/site-packages/bokeh/document/document.py", line 916, in remove_then_invoke
    return callback(*args, **kwargs)
  File "/home/milan/Work/xrviz/venv/lib/python3.6/site-packages/panel/viewable.py", line 653, in _change_event
    self.set_param(**self._process_property_change(events))
  File "/home/milan/Work/xrviz/venv/lib/python3.6/site-packages/param/parameterized.py", line 1219, in inner
    return fn(*args, **kwargs)
  File "/home/milan/Work/xrviz/venv/lib/python3.6/site-packages/param/parameterized.py", line 2572, in set_param
    return self_or_cls.param.set_param(*args,**kwargs)
  File "/home/milan/Work/xrviz/venv/lib/python3.6/site-packages/param/parameterized.py", line 1365, in set_param
    self_._batch_call_watchers()
  File "/home/milan/Work/xrviz/venv/lib/python3.6/site-packages/param/parameterized.py", line 1480, in _batch_call_watchers
    watcher.fn(*events)
  File "/home/milan/Work/xrviz/venv/lib/python3.6/site-packages/xrviz/sigslot.py", line 54, in _signal
    self._emit(self._map[wn], event.new)
  File "/home/milan/Work/xrviz/venv/lib/python3.6/site-packages/xrviz/sigslot.py", line 63, in _emit
    if callback(value) is False:
  File "/home/milan/Work/xrviz/venv/lib/python3.6/site-packages/xrviz/dashboard.py", line 105, in create_plot
    self.create_indexed_graph()
  File "/home/milan/Work/xrviz/venv/lib/python3.6/site-packages/xrviz/dashboard.py", line 144, in create_indexed_graph
    self.output[0] = graph
  File "/home/milan/Work/xrviz/venv/lib/python3.6/site-packages/panel/layout.py", line 219, in __setitem__
    self.objects = new_objects
  File "/home/milan/Work/xrviz/venv/lib/python3.6/site-packages/param/parameterized.py", line 296, in _f
    return f(self, obj, val)
  File "/home/milan/Work/xrviz/venv/lib/python3.6/site-packages/param/parameterized.py", line 861, in __set__
    obj.param._call_watcher(watcher, event)
  File "/home/milan/Work/xrviz/venv/lib/python3.6/site-packages/param/parameterized.py", line 1454, in _call_watcher
    watcher.fn(self_._update_event_type(watcher, event, self_.self_or_cls.param._TRIGGER))
  File "/home/milan/Work/xrviz/venv/lib/python3.6/site-packages/panel/viewable.py", line 604, in param_change
    self._update_model(events, msg, root, model, doc, comm)
  File "/home/milan/Work/xrviz/venv/lib/python3.6/site-packages/panel/layout.py", line 63, in _update_model
    msg[self._rename['objects']] = self._get_objects(model, old, doc, root, comm)
  File "/home/milan/Work/xrviz/venv/lib/python3.6/site-packages/panel/layout.py", line 94, in _get_objects
    child = pane._get_model(doc, root, model, comm)
  File "/home/milan/Work/xrviz/venv/lib/python3.6/site-packages/panel/pane/holoviews.py", line 125, in _get_model
    plot = self._render(doc, comm, root)
  File "/home/milan/Work/xrviz/venv/lib/python3.6/site-packages/panel/pane/holoviews.py", line 150, in _render
    return renderer.get_plot(self.object, **kwargs)
  File "/home/milan/Work/xrviz/venv/lib/python3.6/site-packages/holoviews/plotting/bokeh/renderer.py", line 135, in get_plot
    plot = super(BokehRenderer, self_or_cls).get_plot(obj, renderer, **kwargs)
  File "/home/milan/Work/xrviz/venv/lib/python3.6/site-packages/holoviews/plotting/renderer.py", line 207, in get_plot
    plot.update(init_key)
  File "/home/milan/Work/xrviz/venv/lib/python3.6/site-packages/holoviews/plotting/plot.py", line 595, in update
    return self.initialize_plot()
  File "/home/milan/Work/xrviz/venv/lib/python3.6/site-packages/holoviews/plotting/bokeh/element.py", line 1259, in initialize_plot
    self._init_glyphs(plot, element, ranges, source)
  File "/home/milan/Work/xrviz/venv/lib/python3.6/site-packages/holoviews/plotting/bokeh/element.py", line 1206, in _init_glyphs
    data, mapping, style = self.get_data(element, ranges, style)
  File "/home/milan/Work/xrviz/venv/lib/python3.6/site-packages/holoviews/plotting/bokeh/raster.py", line 207, in get_data
    cmapper = self._get_colormapper(z, element, ranges, style)
  File "/home/milan/Work/xrviz/venv/lib/python3.6/site-packages/holoviews/plotting/bokeh/element.py", line 1674, in _get_colormapper
    palette = process_cmap(cmap, ncolors, categorical=categorical)
  File "/home/milan/Work/xrviz/venv/lib/python3.6/site-packages/holoviews/plotting/util.py", line 894, in process_cmap
    (cmap,providers_checked))
ValueError: Supplied cmap fire not found among matplotlib, bokeh, or colorcet colormaps.
```

Adding matplotlib to requirements.txt fixes this. Let me know if you'd like a PR.

**Comment by martindurant** [comment]
@hdsingh , please clarify install installations with pip (in the blog post and in the README). We should also re-release on conda after your current PRs are in.

**Comment by hdsingh** [comment]
@milancurcic This has been resolved. Now you don't need to add matplotlib to requirements.txt. Also please have a look at the [installation instructions](https://github.com/intake/xrviz/blob/master/README.md#installation).

**Comment by milancurcic** [comment]
Great work, thank you for the prompt turnaround. I was able to install with pip and test successfully.

However, regarding your install instructions: Until you have a stand-alone CLI server executable (e.g. `xrviz` or similar) that is being installed during `pip install`, this is not a useful install sequence. If you do this:

```
pip install git+https://github.com/intake/xrviz
```

Then the examples/* are not installed. Instead, this will work:

```
git clone https://github.com/intake/xrviz
cd xrviz
pip install .
cd examples/
python control_section.py
```

Minor nit-pick: You don't need `.git`, just `pip install git+https://github.com/intake/xrviz` works.

**Comment by martindurant** [comment]
Agree, I already suggested elsewhere that examples/ (or at least one) should be included as a module

**Comment by hdsingh** [comment]
@milancurcic This is being resolved  in https://github.com/intake/xrviz/pull/20.  Thanks!

**Comment by milancurcic** [comment]
Thanks, just tested this with hdsingh/xrviz:example, it works as advertised :). Feel free to close this when merged.

**Comment by hdsingh** [comment]
@martindurant Can this be closed now?

**Comment by gregorhd** [comment]
Hi all, I'm getting this error message in the traceback to a Panel app I'm deploying through voila on Heroku, which uses pip. 

"cet_fire_r" throws the error, "fire_r" does not.

Tried adding matplotlib and colorcet to the requirements.txt (without indicating version numbers) but to no effect.

The requirements.txt reads:

```
voila
nbconvert
ipykernel
cartopy==0.20.3
geoviews==1.9.5
hvplot==0.8.0
panel==0.13.1
rioxarray==0.12.0
scipy==1.9.1
```

Any ideas what I need to add to avail of the (fantastic) colorcet cmaps using pip?

**Comment by martindurant** [comment]
I guess not much development has happened here for a while, and these pinned dependencies are out of date. I would imagine you can safely update all the required packages to latest and have a pretty good chance of everything working. Would be willing to run the experiment?

(@hdsingh , so you still have an interest in this project?)

**Comment by martindurant** [comment]
@philippjfr , is anyone at holo interested in taking this project over, as a counterpart or adjunct to `hvplot.explorer`?

**Comment by philippjfr** [comment]
Good question, I certainly don't have the bandwidth but we should still consider what to do with the codebase. @jbednar and @maximlt, what do you think?

**Comment by maximlt** [comment]
I didn't know/remember xrviz existed. I'd have to try it out to see how close it is to `hvplot.explorer`. I checked pypistats, it had about 60 downloads last month.

**Comment by jbednar** [comment]
xrviz is a great example of where xarray hvPlot Explorer should aim for, but now integrated into hvPlot and supported.

**Comment by martindurant** [comment]
Indeed, xrviz was pretty complete and handy, and I would vote for including it directly in hvplot alongside the dataframe explorer. Of course, that happens to make life easier on me!
